name: Deploy to Bluehost

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BH_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.BH_USER }}@${{ secrets.BH_HOST }} << 'EOF'
            cd /home1/fmnoevmy/public_html
            git pull origin main
            npm install --omit=dev
            pm2 restart server.js || node server.js &
          EOF
