name: Deploy to Bluehost

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BH_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add known hosts
        run: |
          ssh-keyscan -H ${{ secrets.BH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/deploy_key \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=yes \
              ${{ secrets.BH_USER }}@${{ secrets.BH_HOST }} << 'EOF'
            cd /home1/fmnoevmy/public_html/dispatchbase
            git pull origin main
            npm install --omit=dev
            pm2 restart dispatchbase || pm2 start server.js --name dispatchbase
          EOF
